name: hotel_bookings
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.9.0 <4.0.0'
  flutter: 3.35.7

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  auto_route: ^10.2.3
  equatable: ^2.0.7
  flutter_bloc: ^9.1.1
  get_it: ^9.1.0
  http: ^1.6.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  auto_route_generator: ^10.2.6
  bloc_test: ^10.0.0
  build_runner: ^2.7.1
  json_serializable: ^6.11.2
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
  generate: true
